### ISSUE TITLE
:emphasize-lines: 1-5 does nothing.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/sponge_docs_theme#11]
:emphasize-lines: 1

Is a code block directive in order to draw attention to a certain line in a code block.

However the current theme removes the styling given to emphasized lines.

In tomorrow.css adding style properties to line 2

>.highlight .hll { background-color: #f5f5f5;  text-decoration:underline }

Would re-enable us to use this feature.

It's just a matter of what styling would be appropriate, I've tried a few things but couldn't come up with anything I liked.

**Comment by Tzky** [comment]
Resolved in f65d3be, we now use a different background color to emphasize single lines.
