### ISSUE TITLE
Can't print pages

### ISSUE THREAD

**Issue by jamierocks** [SpongePowered/sponge_docs_theme#14]
the nav bar shows half way down on the second page in print preview.

**Comment by lukegb** [comment]
Seems fine for me.

![screenshot_20160324-125755](https://cloud.githubusercontent.com/assets/246745/14017557/23aaeb20-f1c0-11e5-820f-d100700098eb.png)

Given that this type of thing is especially likely to be browser and OS dependent, would you mind spelling out in detail what you're using (and if you can provide screenshots and reproduce on other browsers on the same machine, that'd be marvellous)?

**Comment by jamierocks** [comment]
![image](https://cloud.githubusercontent.com/assets/5103549/14019063/d558766e-f1c8-11e5-95ce-b32f17127024.png)

Windows 7.
Old Chrome release (not sure which).

A fix would be, not scrolling down. I might make a pr to the docs_theme later on, given the chance.

**Comment by Tzky** [comment]
Can confirm this with FF 45.0.2 on Win 8.1.

An easy fix would be the creation of a separate CSS file with ``@media print`` annotation and to disable the topbar there.

**Comment by Tzky** [comment]
@jamierocks can you please try again and report back? 9dd6bb8 should hopefully fix your issue.

**Comment by jamierocks** [comment]
yeah it works great - Thanks ;)
