### ISSUE TITLE
Next Page button should be at the bottom of the page...

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/sponge_docs_theme#7]
I think some Issues currently located in /Spongedocs should belong here as they're design-related. This issue is derived from /SpongeDocs (see: SpongePowered/SpongeDocs#180 )

original Post by @ryantheleach:
Having the next page button at the top of the page means that you need to scroll up to the top of the page every time in order to go to the next page. A small annoyance, but an annoyance none the less.

**Comment by ryantheleach** [comment]
Commenting so this appears in my github participating inbox.

**Comment by Wolfizen** [comment]
I would definitely like to have a next/prev/index box at the bottom of the page as well as the top.

**Comment by Tzky** [comment]
Solved via #12, we have a static topbar now which contains navigation buttons.
